config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :tags
  get '/search' => 'posts#search', :as => 'search_page'
  resources :posts, only: [:index, :show, :search]

  namespace :user do
    resources :posts do
      resources :ratings
    end

    resources :users, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
 
  belongs_to :user
  validates :title, :content, presence: true
  before_validation :preval
  mount_uploader :image, ImageUploader
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy
  has_many :ratings, dependent: :destroy

  include PgSearch::Model
  # multisearchable against: [:title, :content]
  pg_search_scope :search, 
                  against: [:title, :content],
                  associated_against: { user: :full_name,
                                        tags: :name}
  

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

  private
  
  def preval
    self.title = self.title.strip if self.title
    self.content = self.content.strip if self.content
  end


end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :post
  belongs_to :user
  scope :popular, -> { select('post_id, count(post_id) as count').group(:post_id).order('count desc').limit(10) }
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :posts, through: :taggings, dependent: :destroy
    include PgSearch::Model
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :ratings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :bio])
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :bio])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @posts = Post.all.order(:created_at)
    if params[:order] == 'latest'
      @posts = Post.all.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
    elsif params[:order] == 'oldest'
      @posts = Post.all.order(created_at: :asc).paginate(page: params[:page], per_page: 5)
    else
      @posts = Post.all.paginate(page: params[:page], per_page: 5)
    end
  end

  
  def show
  end


  def search
    if params[:search].present?
      @posts= Post.search(params[:search]).paginate(page: params[:page], per_page: 5)
    end
  end

  private

  def posts_params
    params.require(:post).permit(:title, :content, :image, :tag_list)
   end

  def set_post
    @post = Post.find(params[:id])
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
    before_action :authenticate_user!
end

app/controllers/user/posts_controller.rb
class User::PostsController < User::BaseController
  before_action :set_post, only: [:edit, :update, :show, :destroy]


  def index
    @posts = current_user.posts.all.order(:created_at)
    if params[:order] == 'latest'
      @posts = current_user.posts.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
    elsif params[:order] == 'oldest'
      @posts = current_user.posts.order(created_at: :asc).paginate(page: params[:page], per_page: 5)
    else
      @posts = current_user.posts.all.paginate(page: params[:page], per_page: 5)
    end
  end

  
  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(posts_params)
    if @post.save
      flash[:success] = 'Successfully created a new post!'
      redirect_to user_post_path(@post)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end


  def search
    if params[:search].present?
      @posts= Post.search(params[:search]).paginate(page: params[:page], per_page: 5)
    end
  end

  def update
    if @post.update(posts_params)
      flash[:success] = 'Successfully updated the post!'
      redirect_to user_post_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post was deleted"
    redirect_to user_posts_path
  end

  private

  def posts_params
    params.require(:post).permit(:title, :content, :image, :tag_list)
   end

  def set_post
    @post = Post.find(params[:id])
  end
  
end

app/controllers/user/ratings_controller.rb
class User::RatingsController < User::BaseController
  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.ratings.create(user_id: current_user.id)
    end
    redirect_to request.referrer
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else

      @rating.destroy
    end
    redirect_to request.referrer
  end
  
  private  
  
    def find_post
      @post = Post.find(params[:post_id])
    end

    def already_liked?
      Rating.where(user_id: current_user.id, post_id:
      params[:post_id]).exists?
    end

    def find_like
      @rating = @post.ratings.find(params[:id])
    end

end

app/controllers/user/users_controller.rb
class User::UsersController < User::BaseController

  def show
    @user = User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Blog", root_path, class: "navbar-brand", id: "logo" %>
        <div class="navbar-form navbar-left">
          <%= form_tag(search_page_path, method: :get) do %>
          <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %> 
          <%= button_tag "Submit", :class => 'btn btn-default' %>  
          <% end %>
        </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "My posts", user_posts_path %></li>
            <li><%= link_to "Create Post", new_user_post_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.full_name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', user_user_path(current_user) %></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Log in', new_user_session_path %></li>
          <% end %>

        </ul>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
      $(document).on('turbolinks:load', function () {
        tinymce.remove();
        tinymce.init({selector:'.tinymce'});
      });
    </script>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'shared/messages' %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<% provide(:title, "Home") %>

<h1 align="center">All posts</h1>
<div align="center">
    <div class="btn-group" role="group" aria-label="...">
      <button type="button" class="btn btn-default"><%= link_to "Latest", posts_path(order: 'latest') %></button>
      <button type="button" class="btn btn-default"><%= link_to "Oldest", posts_path(order: 'oldest') %></button>
      <button type="button" class="btn btn-default"><%= link_to "Popular", posts_path(:popular) %></button>
    </div>
</div>

<% @posts.each do |post| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="well well-sm">

          <div class="post-title">
            <h2><%= link_to post.title, post_path(post) %></h2>
          </div>

          <div class="post-body">
            <%= truncate(post.content, length: 175) %>
          </div>
          <hr>
          <p><%= post.user.full_name%>, <i> <%= post.created_at.strftime("#{post.created_at.day.ordinalize} %B %Y") %> </i></p>
        </div>

          <% if post.tags.any? %> 
            <% post.tags.each do |tag| %>
              <%= link_to tag.name, tag_path(tag) %>
              <br>
            <% end %>
          <% end %>

        <!-- Ratings -->
        <ol class="breadcrumb">
          <% if user_signed_in? %>
            <% pre_like = post.ratings.find { |rating| rating.user_id == current_user.id} %>
              <% if pre_like %>
                <li><%= button_to 'Unlike', user_post_rating_path(post, pre_like), method: :delete, class:"btn btn-xs btn-danger" %></li>
              <% else %>
                <li><%= button_to 'Like', user_post_ratings_path(post), method: :post, class:"btn btn-xs btn-primary" %></li>
              <% end %>
            <li><%= post.ratings.count %> <%= (post.ratings.count) == 1 ? 'Like' : 'Likes'%></li>
            <% else %>
              <li><%= post.ratings.count %> <%= (post.ratings.count) == 1 ? 'Like' : 'Likes'%></li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
<% end %>

<div align="center">
  <%= will_paginate @posts%>
</div>

app/views/posts/search.html.erb
<% provide(:title, "Search results") %>

<h1 align="center">Search results</h1>

<% if @posts.present? %>
  <% @posts.each do |post| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="well well-sm">

            <div class="post-title">
              <h2><%= link_to post.title, user_post_path(post) %><h2>
            </div>

            <div class="post-body">
              <%= truncate(post.content, length: 175) %>
            </div>

            <hr>
            <p> <%= post.user.full_name%>, <i> <%= post.created_at.strftime("#{post.created_at.day.ordinalize} %B %Y") %> </i> </p>
          </div>

          <% if post.tags.any? %> 
            <p>Tags: <%= link_to post.tag_list, user_post_path(post) %></p>
          <% end %>

          <ol class="breadcrumb">
            <li><%= post.ratings.count %> <%= (post.ratings.count) == 1 ? 'Like' : 'Likes'%></li>
          </ol>
          
        </div>
      </div>
    </div>
  <% end %>

  <div align="center">
    <%= will_paginate @posts%>
  </div>

<% end %>

app/views/posts/show.html.erb
<% provide(:title, "View post") %>

<h2 align="center"><%= @post.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <div class="well well-sm">
    <%= simple_format(@post.content) %>

    <!-- Image -->
    <% if @post.image? %> 
      <hr>
      <%= image_tag (@post.image.url) %>
    <% end %>

    <hr>
    
    <p> <%= @post.user.full_name%>, <i> <%= @post.created_at.strftime("#{@post.created_at.day.ordinalize} %B %Y") %> </i> </p>
  </div>

  <!-- Tags -->
  <% if @post.tags.any? %> 
    <% @post.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
      <br>
    <% end %>
  <% end %>
  

  <!-- Ratings -->
  <ol class="breadcrumb">
  <% if signed_in? %>
      <% pre_like = @post.ratings.find { |rating| rating.user_id == current_user.id} %>
      <% if pre_like %>
        <li><%= button_to 'Unlike', user_post_rating_path(@post, pre_like), method: :delete, class:"btn btn-xs btn-danger" %></li>
      <% else %>
        <li><%= button_to 'Like', user_post_ratings_path(@post), method: :post, class:"btn btn-xs btn-primary" %></li>
      <% end %>
    <% end %>
    <li><%= @post.ratings.count %> <%= (@post.ratings.count) == 1 ? 'Like' : 'Likes'%></li>
  </ol>
  
  <hr>

  <%= link_to 'Back', posts_path, class: "btn btn-xs btn-success" %> |
  <% if current_user && @post.user == current_user %>
    <%= link_to "Edit", edit_user_post_path(@post), class: "btn btn-xs btn-primary" %> |
    <%= link_to "Delete", user_post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if @post.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <div class="panel-body">
      <ul>
       <% @post.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.posts.each do |post| %>
    <li><%= link_to post.title, user_post_path(post) %></li>
  <% end %>
</ul>

app/views/user/posts/_form.html.erb
<%= render 'shared/errors' %>

<div class="row">
 <div class="col-xs-12">
  <%= form_for([:user, @post], :html => {class: "form-horizontal", role: "form"}) do |f| %>

  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of post", autofocus: true %>
   </div>
  </div>

  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :content %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :content, rows: 28, class: "form-control tinymce", placeholder: "Body of post" %>
    <%= tinymce %>
    <%= f.text_field :tag_list, class:"form-control", placeholder: "Tags separated with comma" %>
   </div>
  </div>

  <div class="form-group">
   <div class="control-label col-sm-2">
     <%= f.label :image %>
   </div>
   <div class="col-sm-4">
     <%= f.file_field :image, class: "file-input" %>
   </div>
  <div>

  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div>

  <% end %>
 </div>
</div>

app/views/user/posts/edit.html.erb
<% provide(:title, "Edit post") %>

<h1>Edit post</h1>
<%= render 'form' %>

app/views/user/posts/index.html.erb
<% provide(:title, "Home") %>

<h1 align="center">My posts</h1>
<div align="center">
    <div class="btn-group" role="group" aria-label="...">
      <button type="button" class="btn btn-default"><%= link_to "Latest", user_posts_path(order: 'latest') %></button>
      <button type="button" class="btn btn-default"><%= link_to "Oldest", user_posts_path(order: 'oldest') %></button>
      <button type="button" class="btn btn-default"><%= link_to "Popular", user_posts_path(:popular) %></button>
    </div>
</div>

<% @posts.each do |post| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="well well-sm">

          <div class="post-title">
            <h2><%= link_to post.title, user_post_path(post) %><h2>
          </div>

          <div class="post-body">
            <%= truncate(post.content, length: 175) %>
          </div>

          <hr>
          <p> <%= post.user.full_name%>, <i> <%= post.created_at.strftime("#{post.created_at.day.ordinalize} %B %Y") %> </i> </p>
        </div>

        <% if post.tags.any? %> 
          <% post.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag) %>
            <br>
          <% end %>
        <% end %>

        <ol class="breadcrumb">
          <li><%= post.ratings.count %> <%= (post.ratings.count) == 1 ? 'Like' : 'Likes'%></li>
        </ol>
        
        <hr>
        <div class="post-actions">
          <% if current_user && post.user == current_user %>
            <%= link_to "Edit", edit_user_post_path(post), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete", user_post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete this post?"}, class: "btn btn-xs btn-danger" %>
          <% end %>        
        </div>
      </div>
    </div>
  </div>
<% end %>

<div align="center">
  <%= will_paginate @posts%>
</div>

app/views/user/posts/new.html.erb
<% provide(:title, "Create post") %>

<h1>New post</h1>
<%= render 'form' %>

app/views/user/posts/show.html.erb
<% provide(:title, "View post") %>

<h2 align="center"><%= @post.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <div class="well well-sm">
    <%= simple_format(@post.content) %>

    <!-- Image -->
    <% if @post.image? %> 
      <hr>
      <%= image_tag (@post.image.url) %>
    <% end %>

    <hr>
    
    <p> <%= @post.user.full_name%>, <i> <%= @post.created_at.strftime("#{@post.created_at.day.ordinalize} %B %Y") %> </i> </p>
  </div>

  <!-- Tags -->
  <% if @post.tags.any? %> 
    <% @post.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
      <br>
    <% end %>
  <% end %>
  

  <!-- Ratings -->
  <ol class="breadcrumb">
  <% if signed_in? %>
      <% pre_like = @post.ratings.find { |rating| rating.user_id == current_user.id} %>
      <% if pre_like %>
        <li><%= button_to 'Unlike', user_post_rating_path(@post, pre_like), method: :delete, class:"btn btn-xs btn-danger" %></li>
      <% else %>
        <li><%= button_to 'Like', user_post_ratings_path(@post), method: :post, class:"btn btn-xs btn-primary" %></li>
      <% end %>
    <% end %>
    <li><%= @post.ratings.count %> <%= (@post.ratings.count) == 1 ? 'Like' : 'Likes'%></li>
  </ol>
  
  <hr>

  <%= link_to 'Back', posts_path, class: "btn btn-xs btn-success" %> |
  <% if current_user && @post.user == current_user %>
    <%= link_to "Edit", edit_user_post_path(@post), class: "btn btn-xs btn-primary" %> |
    <%= link_to "Delete", user_post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
  <% end %>
</div>

app/views/user/users/show.html.erb
<% provide(:title, "My profile") %>

<div class="jumbotron">
  <div class="container">
<h1> <%= current_user.full_name %> </h1>
  <p><%= current_user.bio %></p>
  <p> Email: <%= current_user.email %> </p>
  <p><%= link_to 'Edit profile', edit_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
  
</div>